---
collections:
  - name: mgcdrd.infrabase
    source: https://github.com/mgcdrd/infrabase.git
    type: git
    version: v0.15.2

  - name: ansible.posix
    version: ">=1.5.0"

  - name: community.general
    version: ">=11.0.0"
