---
collections:
  - name: mgcdrd.infrabase
    source: https://github.com/mgcdrd/infrabase.git
    type: git
    version: v0.7.0

  - name: ansible.posix
    version: ">=1.5.0"

  - name: community.general
    version: ">=9.0.0"
